/**
 * Root layout: the HTML shell wrapped around every page.
 *
 * WHAT: Sets fonts, page metadata and the theme-before-paint script, then renders
 *   `<Providers><AppShell>{page}</AppShell></Providers>`.
 * LAYER: Next.js App Router layout (a SERVER component: no "use client", no hooks).
 * CALLED BY: Next.js itself, for every route.
 * CALLS: `Providers` (all client-side contexts), `AppShell` (sidebar/navbar), global CSS.
 * MERN EQUIVALENT: `public/index.html` plus the top of `index.js` / `App.js` where providers and
 *   the layout are mounted.
 * INTERVIEW: a layout is NOT remounted when you navigate between pages, so the sidebar and its
 * state persist while only `children` (the page) changes.
 */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppShell } from "@/shared/components/layout/AppShell";
import { Providers } from "@/shared/components/Providers";
import { DARK_CLASS, SYSTEM_DARK_QUERY, THEME_STORAGE_KEY } from "@/shared/utils/theme";
import "@/styles/globals.css";

// Inter matches the Fireflies UI font (docs/reference/colors.md §4); exposed as a CSS variable
// so globals.css can feed it to Tailwind's `font-sans`.
// `next/font` downloads the font at build time and self-hosts it (no request to Google at runtime).
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Next.js reads this exported object to build the <title> and <meta> tags (no <Helmet> needed).
export const metadata: Metadata = {
  title: "Fireflies Clone",
  description: "Meeting library, transcripts and AI summaries",
  icons: {
    icon: "/icon.svg",
  },
};

// Runs before first paint so a saved "light"/"system" choice never flashes dark. Mirrors
// resolveTheme() in shared/utils/theme.ts; anything unreadable leaves the default dark class.
// INTERVIEW: a tiny inline script that runs BEFORE React hydrates. It reads the saved theme from
// localStorage and sets the `dark` class on <html>, so a user who chose light mode never sees a
// dark flash while the JavaScript bundle loads.
const THEME_INIT_SCRIPT = `try{var t=localStorage.getItem("${THEME_STORAGE_KEY}");var d=t==="system"?matchMedia("${SYSTEM_DARK_QUERY}").matches:t!=="light";document.documentElement.classList.toggle("${DARK_CLASS}",d)}catch(e){}`;

// `LayoutProps<"/">` is a global type generated by Next.js; `children` is the current page.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    // `dark` is the default; ThemeProvider and THEME_INIT_SCRIPT change <html>'s class before
    // hydration, hence suppressHydrationWarning.
    <html
      lang="en"
      className={`${inter.variable} dark h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="h-full">
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
