from pathlib import Path

import pytest
from alembic.config import Config

from alembic import command
from app.core.config import settings

BACKEND_DIR = Path(__file__).resolve().parents[1]


def test_migrations_match_models(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Upgrading an empty DB to head must yield exactly the schema the models describe.

    Catches a model change that was never turned into a migration (and vice versa).
    """
    # env.py reads the URL from settings, so point settings at a throwaway file DB.
    monkeypatch.setattr(settings, "DATABASE_URL", f"sqlite:///{tmp_path / 'migrations.db'}")
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.attributes["configure_logger"] = False

    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected on any drift
    command.downgrade(config, "base")
