"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 23:31:23.183069

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-edited after autogenerate: enum CHECK constraints come from sa.Enum(create_constraint=True)
    (named via the naming convention, e.g. ck_meetings_meeting_source); autogenerate also rendered
    them as explicit CheckConstraints, which would have created each one three times.

    Reading guide (comments only; no behaviour changed):
    - Tables are created parents first (participants, tags, users, then meetings, then the
      tables that point at meetings) because a foreign key target must already exist.
    - `op.f("name")` marks a constraint name as final, so the naming convention in
      core/database.py is not applied twice.
    - SQLite cannot add indexes with plain ALTER, so they go through `batch_alter_table`.
    - INTERVIEW: a migration freezes the schema as of this revision; it deliberately does not
      import app models, so later model refactors can never break it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar_color", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint("email", name=op.f("uq_participants_email")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("meeting_date", sa.DateTime(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "seed",
                "upload",
                "paste",
                "form",
                name="meeting_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.Enum(
                "zoom",
                "google_meet",
                "teams",
                "upload",
                name="meeting_platform",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_meetings_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.create_index("ix_meetings_owner_date", ["owner_id", "meeting_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_meetings_title"), ["title"], unique=False)

    op.create_table(
        "chapters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_chapters_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint("meeting_id", "position", name=op.f("uq_chapters_meeting_id")),
    )
    op.create_table(
        "meeting_participants",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "host",
                "attendee",
                name="participant_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="attendee",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_participants_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_meeting_participants_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "meeting_id", "participant_id", name=op.f("pk_meeting_participants")
        ),
    )
    with op.batch_alter_table("meeting_participants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_meeting_participants_participant_id"), ["participant_id"], unique=False
        )

    op.create_table(
        "meeting_tags",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_tags_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_meeting_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("meeting_id", "tag_id", name=op.f("pk_meeting_tags")),
    )
    with op.batch_alter_table("meeting_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meeting_tags_tag_id"), ["tag_id"], unique=False)

    op.create_table(
        "summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("bullet_points", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("keywords", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "generated_by",
            sa.Enum(
                "seed",
                "mock",
                "llm",
                name="generated_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_summaries_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summaries")),
        sa.UniqueConstraint("meeting_id", name=op.f("uq_summaries_meeting_id")),
    )
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("speaker_label", sa.String(length=100), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_ms >= start_ms", name=op.f("ck_transcript_segments_end_after_start")
        ),
        sa.CheckConstraint(
            "start_ms >= 0", name=op.f("ck_transcript_segments_start_ms_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_transcript_segments_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_transcript_segments_participant_id_participants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint(
            "meeting_id", "position", name=op.f("uq_transcript_segments_meeting_id")
        ),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index("ix_segments_meeting_start", ["meeting_id", "start_ms"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transcript_segments_participant_id"), ["participant_id"], unique=False
        )

    op.create_table(
        "action_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("source_segment_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["participants.id"],
            name=op.f("fk_action_items_assignee_id_participants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_action_items_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id"],
            ["transcript_segments.id"],
            name=op.f("fk_action_items_source_segment_id_transcript_segments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
    )
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_items_assignee_id"), ["assignee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_items_meeting_id"), ["meeting_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_items_source_segment_id"), ["source_segment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: undo `upgrade` in reverse order (children before their parents)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_items_source_segment_id"))
        batch_op.drop_index(batch_op.f("ix_action_items_meeting_id"))
        batch_op.drop_index(batch_op.f("ix_action_items_assignee_id"))

    op.drop_table("action_items")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segments_participant_id"))
        batch_op.drop_index("ix_segments_meeting_start")

    op.drop_table("transcript_segments")
    op.drop_table("summaries")
    with op.batch_alter_table("meeting_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meeting_tags_tag_id"))

    op.drop_table("meeting_tags")
    with op.batch_alter_table("meeting_participants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meeting_participants_participant_id"))

    op.drop_table("meeting_participants")
    op.drop_table("chapters")
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meetings_title"))
        batch_op.drop_index("ix_meetings_owner_date")

    op.drop_table("meetings")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("participants")
    # ### end Alembic commands ###
